---
  - name: Create sources directory if it does not exist
    file:
      path: /home/ubuntu/sources
      state: directory
  
  - name: Get stats of the arduino-cli binary to check it exists 
    ansible.builtin.stat:
      path: /usr/local/bin/arduino-cli
    register: st
  
  - name: Print a debug message if arduino-cli not installed
    ansible.builtin.debug:
      msg: "arduino-cli is not installed"
    when: st.stat.exists == False
    
  - git:
      repo: https://github.com/practable/truss.git
      dest: /home/ubuntu/sources/truss
      update: yes
     
  - name: Update core index arduino
    command: arduino-cli core update-index

  - name: Install samd core arduino
    command: arduino-cli core install arduino:samd

  - name: Compile spinner firmware
    command: arduino-cli compile --fqbn arduino:samd:nano_33_iot MiniTruss/ --libraries /home/ubuntu/sources/truss/fw/libraries
    args:
      chdir: /home/ubuntu/sources/truss/fw

  - name: Load spinner firmware onto arduino
    command: arduino-cli upload --port /dev/ttyACM0 --fqbn arduino:samd:nano_33_iot MiniTruss/
    args:
      chdir: /home/pi/sources/truss/fw
    

